apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chartTestDatabase.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
