apiVersion: v2
name: chartTest
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: frontend
    version: 0.1.0
    repository: file://charts/frontend
  - name: backend
    version: 0.1.0
    repository: file://charts/backend
  - name: mongodb
    version: 0.1.0
    repository: file://charts/mongodb
